### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by yyny1789** [WeeTom/MDIHorizontalSectionTableViewController#1]
我看了这个项目的源码，有一些问题想请教一下您。
1.我查看了reloadData 方法，发现里面是直接创建 self.sections.count 数量的MDITableViewController，如果很多的话，没有重用怎么办？
2.您说的这个项目是根据产品需求，我对这个需求有点感兴趣，方便告诉下app 的名字吗？

期待您的回复~

**Comment by WeeTom** [comment]
很高兴收到的Issue
1. 目前确实没有重用，因为还没想清楚怎么重用，尤其翻来翻去后页面的状态变化，需要记录不少。
出于实际使用场景，并不会有太多section，撑死20个把，所以没有考虑重用。
2. 项目是明道，具体使用点在任务中心项目内的阶段视图。

**Comment by yyny1789** [comment]
恩呢，感谢您的回答，我在app内找到了。
同时反馈给你2个小问题（个人感觉哈）
![img_3475](https://cloud.githubusercontent.com/assets/7362823/9434850/2ce5abc8-4a75-11e5-81cb-dd0e22b2bf18.PNG)
![img_3476](https://cloud.githubusercontent.com/assets/7362823/9434849/2cd7f6ae-4a75-11e5-8d47-66a153e84dde.PNG)

第一个注册后，没有直接登录，或者当前页面没有直接登录按钮，感觉有点不爽。
第二个的那个弹出view，下面有空白，有点受不了哦（小强迫症...
纯属个人意见~

**Comment by WeeTom** [comment]
嗷，谢谢。
因为注册目前还是通过H5页面，所以没能直接登录
第二个我还比较喜欢留一段白，哈哈

**Comment by yyny1789** [comment]
O(∩_∩)O哈哈哈~
